/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package com.shippo.sdk.models.operations;


public class ListWebhooksRequestBuilder {

    private final SDKMethodInterfaces.MethodCallListWebhooks sdk;

    public ListWebhooksRequestBuilder(SDKMethodInterfaces.MethodCallListWebhooks sdk) {
        this.sdk = sdk;
    }

    public ListWebhooksResponse call() throws Exception {

        return sdk.listWebhooksDirect();
    }
}
