/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package com.goshippo.shippo_sdk.models.components;

import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;

/**
 * CustomsDeclarationType - Party to be billed for duties.
 */
public enum CustomsDeclarationType {
    SENDER("SENDER"),
    RECIPIENT("RECIPIENT"),
    THIRD_PARTY("THIRD_PARTY");

    @JsonValue
    private final String value;

    private CustomsDeclarationType(String value) {
        this.value = value;
    }
    
    public String value() {
        return value;
    }
    
    public static Optional<CustomsDeclarationType> fromValue(String value) {
        for (CustomsDeclarationType o: CustomsDeclarationType.values()) {
            if (Objects.deepEquals(o.value, value)) {
                return Optional.of(o);
            }
        }
        return Optional.empty();
    }
}
