/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package com.goshippo.shippo_sdk.models.components;

import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;

/**
 * ServiceLevelLasershipEnum - |Token | Service name|
 * |:---|:---|
 * | lasership_routed_delivery | Routed Delivery|
 * 
 */
public enum ServiceLevelLasershipEnum {
    LASERSHIP_ROUTED_DELIVERY("lasership_routed_delivery");

    @JsonValue
    private final String value;

    private ServiceLevelLasershipEnum(String value) {
        this.value = value;
    }
    
    public String value() {
        return value;
    }
    
    public static Optional<ServiceLevelLasershipEnum> fromValue(String value) {
        for (ServiceLevelLasershipEnum o: ServiceLevelLasershipEnum.values()) {
            if (Objects.deepEquals(o.value, value)) {
                return Optional.of(o);
            }
        }
        return Optional.empty();
    }
}
