/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package com.goshippo.sdk.models.operations;

import com.goshippo.sdk.utils.Utils;

public class ListCarrierAccountsRequestBuilder {

    private ListCarrierAccountsRequest request;
    private final SDKMethodInterfaces.MethodCallListCarrierAccounts sdk;

    public ListCarrierAccountsRequestBuilder(SDKMethodInterfaces.MethodCallListCarrierAccounts sdk) {
        this.sdk = sdk;
    }

    public ListCarrierAccountsRequestBuilder request(ListCarrierAccountsRequest request) {
        Utils.checkNotNull(request, "request");
        this.request = request;
        return this;
    }

    public ListCarrierAccountsResponse call() throws Exception {

        return sdk.list(
            request);
    }
}
