/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.goshippo.shippo_sdk.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.goshippo.shippo_sdk.models.components.EmbeddedAuthorization;
import com.goshippo.shippo_sdk.utils.Response;
import com.goshippo.shippo_sdk.utils.Utils;
import java.io.InputStream;
import java.lang.Integer;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.net.http.HttpResponse;
import java.util.Optional;


public class CreateEmbeddedAuthorizationResponse implements Response {
    /**
     * HTTP response content type for this operation
     */
    private String contentType;

    /**
     * HTTP response status code for this operation
     */
    private int statusCode;

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    private HttpResponse<InputStream> rawResponse;

    /**
     * Success
     */
    private Optional<? extends EmbeddedAuthorization> embeddedAuthorization;

    @JsonCreator
    public CreateEmbeddedAuthorizationResponse(
            String contentType,
            int statusCode,
            HttpResponse<InputStream> rawResponse,
            Optional<? extends EmbeddedAuthorization> embeddedAuthorization) {
        Utils.checkNotNull(contentType, "contentType");
        Utils.checkNotNull(statusCode, "statusCode");
        Utils.checkNotNull(rawResponse, "rawResponse");
        Utils.checkNotNull(embeddedAuthorization, "embeddedAuthorization");
        this.contentType = contentType;
        this.statusCode = statusCode;
        this.rawResponse = rawResponse;
        this.embeddedAuthorization = embeddedAuthorization;
    }
    
    public CreateEmbeddedAuthorizationResponse(
            String contentType,
            int statusCode,
            HttpResponse<InputStream> rawResponse) {
        this(contentType, statusCode, rawResponse,
            Optional.empty());
    }

    /**
     * HTTP response content type for this operation
     */
    @JsonIgnore
    public String contentType() {
        return contentType;
    }

    /**
     * HTTP response status code for this operation
     */
    @JsonIgnore
    public int statusCode() {
        return statusCode;
    }

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    @JsonIgnore
    public HttpResponse<InputStream> rawResponse() {
        return rawResponse;
    }

    /**
     * Success
     */
    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<EmbeddedAuthorization> embeddedAuthorization() {
        return (Optional<EmbeddedAuthorization>) embeddedAuthorization;
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * HTTP response content type for this operation
     */
    public CreateEmbeddedAuthorizationResponse withContentType(String contentType) {
        Utils.checkNotNull(contentType, "contentType");
        this.contentType = contentType;
        return this;
    }

    /**
     * HTTP response status code for this operation
     */
    public CreateEmbeddedAuthorizationResponse withStatusCode(int statusCode) {
        Utils.checkNotNull(statusCode, "statusCode");
        this.statusCode = statusCode;
        return this;
    }

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    public CreateEmbeddedAuthorizationResponse withRawResponse(HttpResponse<InputStream> rawResponse) {
        Utils.checkNotNull(rawResponse, "rawResponse");
        this.rawResponse = rawResponse;
        return this;
    }

    /**
     * Success
     */
    public CreateEmbeddedAuthorizationResponse withEmbeddedAuthorization(EmbeddedAuthorization embeddedAuthorization) {
        Utils.checkNotNull(embeddedAuthorization, "embeddedAuthorization");
        this.embeddedAuthorization = Optional.ofNullable(embeddedAuthorization);
        return this;
    }


    /**
     * Success
     */
    public CreateEmbeddedAuthorizationResponse withEmbeddedAuthorization(Optional<? extends EmbeddedAuthorization> embeddedAuthorization) {
        Utils.checkNotNull(embeddedAuthorization, "embeddedAuthorization");
        this.embeddedAuthorization = embeddedAuthorization;
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        CreateEmbeddedAuthorizationResponse other = (CreateEmbeddedAuthorizationResponse) o;
        return 
            Utils.enhancedDeepEquals(this.contentType, other.contentType) &&
            Utils.enhancedDeepEquals(this.statusCode, other.statusCode) &&
            Utils.enhancedDeepEquals(this.rawResponse, other.rawResponse) &&
            Utils.enhancedDeepEquals(this.embeddedAuthorization, other.embeddedAuthorization);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            contentType, statusCode, rawResponse,
            embeddedAuthorization);
    }
    
    @Override
    public String toString() {
        return Utils.toString(CreateEmbeddedAuthorizationResponse.class,
                "contentType", contentType,
                "statusCode", statusCode,
                "rawResponse", rawResponse,
                "embeddedAuthorization", embeddedAuthorization);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String contentType;

        private Integer statusCode;

        private HttpResponse<InputStream> rawResponse;

        private Optional<? extends EmbeddedAuthorization> embeddedAuthorization = Optional.empty();

        private Builder() {
          // force use of static builder() method
        }


        /**
         * HTTP response content type for this operation
         */
        public Builder contentType(String contentType) {
            Utils.checkNotNull(contentType, "contentType");
            this.contentType = contentType;
            return this;
        }


        /**
         * HTTP response status code for this operation
         */
        public Builder statusCode(int statusCode) {
            Utils.checkNotNull(statusCode, "statusCode");
            this.statusCode = statusCode;
            return this;
        }


        /**
         * Raw HTTP response; suitable for custom response parsing
         */
        public Builder rawResponse(HttpResponse<InputStream> rawResponse) {
            Utils.checkNotNull(rawResponse, "rawResponse");
            this.rawResponse = rawResponse;
            return this;
        }


        /**
         * Success
         */
        public Builder embeddedAuthorization(EmbeddedAuthorization embeddedAuthorization) {
            Utils.checkNotNull(embeddedAuthorization, "embeddedAuthorization");
            this.embeddedAuthorization = Optional.ofNullable(embeddedAuthorization);
            return this;
        }

        /**
         * Success
         */
        public Builder embeddedAuthorization(Optional<? extends EmbeddedAuthorization> embeddedAuthorization) {
            Utils.checkNotNull(embeddedAuthorization, "embeddedAuthorization");
            this.embeddedAuthorization = embeddedAuthorization;
            return this;
        }

        public CreateEmbeddedAuthorizationResponse build() {

            return new CreateEmbeddedAuthorizationResponse(
                contentType, statusCode, rawResponse,
                embeddedAuthorization);
        }

    }
}
