/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.goshippo.shippo_sdk.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.goshippo.shippo_sdk.utils.SpeakeasyMetadata;
import com.goshippo.shippo_sdk.utils.Utils;
import java.lang.Override;
import java.lang.String;


public class GetAddressRequest {
    /**
     * Object ID of the address
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=AddressId")
    private String addressId;

    @JsonCreator
    public GetAddressRequest(
            String addressId) {
        Utils.checkNotNull(addressId, "addressId");
        this.addressId = addressId;
    }

    /**
     * Object ID of the address
     */
    @JsonIgnore
    public String addressId() {
        return addressId;
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * Object ID of the address
     */
    public GetAddressRequest withAddressId(String addressId) {
        Utils.checkNotNull(addressId, "addressId");
        this.addressId = addressId;
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        GetAddressRequest other = (GetAddressRequest) o;
        return 
            Utils.enhancedDeepEquals(this.addressId, other.addressId);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            addressId);
    }
    
    @Override
    public String toString() {
        return Utils.toString(GetAddressRequest.class,
                "addressId", addressId);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String addressId;

        private Builder() {
          // force use of static builder() method
        }


        /**
         * Object ID of the address
         */
        public Builder addressId(String addressId) {
            Utils.checkNotNull(addressId, "addressId");
            this.addressId = addressId;
            return this;
        }

        public GetAddressRequest build() {

            return new GetAddressRequest(
                addressId);
        }

    }
}
