/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.goshippo.shippo_sdk.models.operations;

import static com.goshippo.shippo_sdk.operations.Operations.RequestOperation;

import com.goshippo.shippo_sdk.SDKConfiguration;
import com.goshippo.shippo_sdk.operations.GetRate;
import com.goshippo.shippo_sdk.utils.Headers;
import com.goshippo.shippo_sdk.utils.Utils;
import java.lang.String;

public class GetRateRequestBuilder {

    private String rateId;
    private final SDKConfiguration sdkConfiguration;
    private final Headers _headers = new Headers(); 

    public GetRateRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
    }

    public GetRateRequestBuilder rateId(String rateId) {
        Utils.checkNotNull(rateId, "rateId");
        this.rateId = rateId;
        return this;
    }


    private GetRateRequest buildRequest() {

        GetRateRequest request = new GetRateRequest(rateId);

        return request;
    }

    public GetRateResponse call() {
        
        RequestOperation<GetRateRequest, GetRateResponse> operation
              = new GetRate.Sync(sdkConfiguration, _headers);
        GetRateRequest request = buildRequest();

        return operation.handleResponse(operation.doRequest(request));
    }
}
