/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.goshippo.shippo_sdk.models.operations;

import static com.goshippo.shippo_sdk.operations.Operations.RequestOperation;

import com.goshippo.shippo_sdk.SDKConfiguration;
import com.goshippo.shippo_sdk.operations.GetWebhook;
import com.goshippo.shippo_sdk.utils.Headers;
import com.goshippo.shippo_sdk.utils.Utils;
import java.lang.String;

public class GetWebhookRequestBuilder {

    private String webhookId;
    private final SDKConfiguration sdkConfiguration;
    private final Headers _headers = new Headers(); 

    public GetWebhookRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
    }

    public GetWebhookRequestBuilder webhookId(String webhookId) {
        Utils.checkNotNull(webhookId, "webhookId");
        this.webhookId = webhookId;
        return this;
    }


    private GetWebhookRequest buildRequest() {

        GetWebhookRequest request = new GetWebhookRequest(webhookId);

        return request;
    }

    public GetWebhookResponse call() {
        
        RequestOperation<GetWebhookRequest, GetWebhookResponse> operation
              = new GetWebhook.Sync(sdkConfiguration, _headers);
        GetWebhookRequest request = buildRequest();

        return operation.handleResponse(operation.doRequest(request));
    }
}
