/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.goshippo.shippo_sdk.models.operations;

import com.fasterxml.jackson.annotation.JsonTypeInfo.As;
import com.fasterxml.jackson.annotation.JsonTypeInfo.Id;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.databind.annotation.JsonTypeIdResolver;
import java.lang.String;

/**
 * RegisterCarrierAccountRequestBody
 * 
 * <p>The body of the request.
 */
@JsonTypeInfo(
        use = Id.CUSTOM,
        property = "carrier",
        include = As.EXISTING_PROPERTY,
        visible = true,
        defaultImpl = UnknownRegisterCarrierAccountRequestBody.class
)
@JsonTypeIdResolver(RegisterCarrierAccountRequestBodyTypeIdResolver.class)
public interface RegisterCarrierAccountRequestBody {

    String carrier();

}

