workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    my-first-source:
        inputs:
            - location: https://docs.goshippo.com/spec/shippoapi/public-api.yaml
        registry:
            location: registry.speakeasyapi.dev/shippo/shippo/my-first-source
targets:
    my-first-target:
        target: java
        source: my-first-source
        publish:
            java:
                ossrhUsername: $ossrh_username
                ossrhPassword: $ossrh_password
                gpgSecretKey: $java_gpg_secret_key
                gpgPassPhrase: $java_gpg_passphrase
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/shippo/shippo/my-first-source-java-code-samples
            blocking: false
