/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.shippo.sdk.models.components;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.core.type.TypeReference;
import com.shippo.sdk.utils.Utils;
import java.io.InputStream;
import java.lang.Deprecated;
import java.math.BigDecimal;
import java.math.BigInteger;

import java.time.OffsetDateTime;
import java.time.LocalDate;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.shippo.sdk.utils.TypedObject;
import com.shippo.sdk.utils.Utils.JsonShape;


@JsonDeserialize(using = CarrierAccountParameters._Deserializer.class)
public class CarrierAccountParameters {

    @com.fasterxml.jackson.annotation.JsonValue
    private TypedObject value;
    
    private CarrierAccountParameters(TypedObject value) {
        this.value = value;
    }

    public static CarrierAccountParameters of(java.util.Map<String, java.lang.Object> value) {
        Utils.checkNotNull(value, "value");
        return new CarrierAccountParameters(TypedObject.of(value, JsonShape.DEFAULT, new TypeReference<java.util.Map<String, java.lang.Object>>(){}));
    }

    public static CarrierAccountParameters of(FedExConnectExistingOwnAccountParameters value) {
        Utils.checkNotNull(value, "value");
        return new CarrierAccountParameters(TypedObject.of(value, JsonShape.DEFAULT, new TypeReference<FedExConnectExistingOwnAccountParameters>(){}));
    }

    public static CarrierAccountParameters of(UPSConnectExistingOwnAccountParameters value) {
        Utils.checkNotNull(value, "value");
        return new CarrierAccountParameters(TypedObject.of(value, JsonShape.DEFAULT, new TypeReference<UPSConnectExistingOwnAccountParameters>(){}));
    }
    
    /**
     * Returns an instance of one of these types:
     * <ul>
     * <li>{@code java.util.Map<String, java.lang.Object>}</li>
     * <li>{@code FedExConnectExistingOwnAccountParameters}</li>
     * <li>{@code UPSConnectExistingOwnAccountParameters}</li>
     * </ul>
     * 
     * <p>Use {@code instanceof} to determine what type is returned. For example:
     * 
     * <pre>
     * if (obj.value() instanceof String) {
     *     String answer = (String) obj.value();
     *     System.out.println("answer=" + answer);
     * }
     * </pre>
     * 
     * @return value of oneOf type
     **/ 
    public java.lang.Object value() {
        return value.value();
    }    
    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        CarrierAccountParameters other = (CarrierAccountParameters) o;
        return java.util.Objects.deepEquals(this.value.value(), other.value.value()); 
    }
    
    @Override
    public int hashCode() {
        return java.util.Objects.hash(value.value());
    }
    
    @SuppressWarnings("serial")
    public static final class _Deserializer extends com.shippo.sdk.utils.OneOfDeserializer<CarrierAccountParameters> {

        public _Deserializer() {
            super(CarrierAccountParameters.class,
                  Utils.TypeReferenceWithShape.of(new TypeReference<java.util.Map<String, java.lang.Object>>() {}, Utils.JsonShape.DEFAULT),
                  Utils.TypeReferenceWithShape.of(new TypeReference<FedExConnectExistingOwnAccountParameters>() {}, Utils.JsonShape.DEFAULT),
                  Utils.TypeReferenceWithShape.of(new TypeReference<UPSConnectExistingOwnAccountParameters>() {}, Utils.JsonShape.DEFAULT));
        }
    }
    
    @Override
    public String toString() {
        return Utils.toString(CarrierAccountParameters.class,
                "value", value);
    }
 
}
