/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package com.shippo.sdk.models.components;

import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;

/**
 * CustomsTaxIdentificationType - Type of tax identification.
 * * `EIN` - Employer Identification Number, also known as a Federal Tax Identification Number.
 * * `VAT` - Value Added Tax identification number.
 * * `IOSS` - Import One-Stop Shop
 * * `ARN` - Australian Taxation Office Reference Number
 */
public enum CustomsTaxIdentificationType {
    EIN("EIN"),
    VAT("VAT"),
    IOSS("IOSS"),
    ARN("ARN");

    @JsonValue
    private final String value;

    private CustomsTaxIdentificationType(String value) {
        this.value = value;
    }
    
    public String value() {
        return value;
    }
}
