/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.shippo.sdk.models.components;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.core.type.TypeReference;
import com.shippo.sdk.utils.Utils;
import java.io.InputStream;
import java.lang.Deprecated;
import java.math.BigDecimal;
import java.math.BigInteger;

/**
 * ParcelTemplateDPDUKEnum - |Token | Name | Dimensions|
 * |:---|:---|:---|
 * | DPD_UK_Express_Pak| DPD UK Express Pak | 530.00 x 400.00 x 100.00 mm|
 * 
 */
public enum ParcelTemplateDPDUKEnum {
    DPDUK_EXPRESS_PAK("DPD_UK_Express_Pak");

    @JsonValue
    private final String value;

    private ParcelTemplateDPDUKEnum(String value) {
        this.value = value;
    }
    
    public String value() {
        return value;
    }
}
