/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package com.shippo.sdk.models.components;

import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;

/**
 * PreferredDeliveryTimeframe - Required for DHL Germany Paket Sameday. Designates a desired timeframe for delivery. Format is `HHMMHHMM`
 */
public enum PreferredDeliveryTimeframe {
    TEN_MILLION_ONE_THOUSAND_TWO_HUNDRED("10001200"),
    TWELVE_MILLION_ONE_THOUSAND_FOUR_HUNDRED("12001400"),
    FOURTEEN_MILLION_ONE_THOUSAND_SIX_HUNDRED("14001600"),
    SIXTEEN_MILLION_ONE_THOUSAND_EIGHT_HUNDRED("16001800"),
    EIGHTEEN_MILLION_TWO_THOUSAND("18002000"),
    NINETEEN_MILLION_TWO_THOUSAND_ONE_HUNDRED("19002100");

    @JsonValue
    private final String value;

    private PreferredDeliveryTimeframe(String value) {
        this.value = value;
    }
    
    public String value() {
        return value;
    }
}
