/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.shippo.sdk.models.components;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.core.type.TypeReference;
import com.shippo.sdk.utils.Utils;
import java.io.InputStream;
import java.lang.Deprecated;
import java.math.BigDecimal;
import java.math.BigInteger;

/**
 * ServiceLevelBetterTrucksEnum - |Token | Service name|
 * |:---|:---|
 * | better_trucks_same_day | Same Day|
 * | better_trucks_next_day | Next Day|
 * 
 */
public enum ServiceLevelBetterTrucksEnum {
    BETTER_TRUCKS_SAME_DAY("better_trucks_same_day"),
    BETTER_TRUCKS_NEXT_DAY("better_trucks_next_day");

    @JsonValue
    private final String value;

    private ServiceLevelBetterTrucksEnum(String value) {
        this.value = value;
    }
    
    public String value() {
        return value;
    }
}
