/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package com.shippo.sdk.models.components;

import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;

/**
 * WebhookEventTypeEnum - Type of event that triggered the webhook.
 */
public enum WebhookEventTypeEnum {
    TRANSACTION_CREATED("transaction_created"),
    TRANSACTION_UPDATED("transaction_updated"),
    TRACK_UPDATED("track_updated"),
    BATCH_CREATED("batch_created"),
    BATCH_PURCHASED("batch_purchased"),
    ALL("all");

    @JsonValue
    private final String value;

    private WebhookEventTypeEnum(String value) {
        this.value = value;
    }
    
    public String value() {
        return value;
    }
}
