/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.shippo.shippo_java_sdk.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.core.type.TypeReference;
import com.shippo.shippo_java_sdk.utils.SpeakeasyMetadata;
import com.shippo.shippo_java_sdk.utils.Utils;
import java.io.InputStream;
import java.lang.Deprecated;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.Optional;


public class GetAddressRequest {

    /**
     * Object ID of the address
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=AddressId")
    private String addressId;

    /**
     * String used to pick a non-default API version to use
     */
    @SpeakeasyMetadata("header:style=simple,explode=false,name=SHIPPO-API-VERSION")
    private Optional<? extends String> shippoApiVersion;

    @JsonCreator
    public GetAddressRequest(
            String addressId,
            Optional<? extends String> shippoApiVersion) {
        Utils.checkNotNull(addressId, "addressId");
        Utils.checkNotNull(shippoApiVersion, "shippoApiVersion");
        this.addressId = addressId;
        this.shippoApiVersion = shippoApiVersion;
    }
    
    public GetAddressRequest(
            String addressId) {
        this(addressId, Optional.empty());
    }

    /**
     * Object ID of the address
     */
    @JsonIgnore
    public String addressId() {
        return addressId;
    }

    /**
     * String used to pick a non-default API version to use
     */
    @JsonIgnore
    public Optional<? extends String> shippoApiVersion() {
        return shippoApiVersion;
    }

    public final static Builder builder() {
        return new Builder();
    }

    /**
     * Object ID of the address
     */
    public GetAddressRequest withAddressId(String addressId) {
        Utils.checkNotNull(addressId, "addressId");
        this.addressId = addressId;
        return this;
    }

    /**
     * String used to pick a non-default API version to use
     */
    public GetAddressRequest withShippoApiVersion(String shippoApiVersion) {
        Utils.checkNotNull(shippoApiVersion, "shippoApiVersion");
        this.shippoApiVersion = Optional.ofNullable(shippoApiVersion);
        return this;
    }

    /**
     * String used to pick a non-default API version to use
     */
    public GetAddressRequest withShippoApiVersion(Optional<? extends String> shippoApiVersion) {
        Utils.checkNotNull(shippoApiVersion, "shippoApiVersion");
        this.shippoApiVersion = shippoApiVersion;
        return this;
    }
    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        GetAddressRequest other = (GetAddressRequest) o;
        return 
            java.util.Objects.deepEquals(this.addressId, other.addressId) &&
            java.util.Objects.deepEquals(this.shippoApiVersion, other.shippoApiVersion);
    }
    
    @Override
    public int hashCode() {
        return java.util.Objects.hash(
            addressId,
            shippoApiVersion);
    }
    
    @Override
    public String toString() {
        return Utils.toString(GetAddressRequest.class,
                "addressId", addressId,
                "shippoApiVersion", shippoApiVersion);
    }
    
    public final static class Builder {
 
        private String addressId;
 
        private Optional<? extends String> shippoApiVersion = Optional.empty();  
        
        private Builder() {
          // force use of static builder() method
        }

        /**
         * Object ID of the address
         */
        public Builder addressId(String addressId) {
            Utils.checkNotNull(addressId, "addressId");
            this.addressId = addressId;
            return this;
        }

        /**
         * String used to pick a non-default API version to use
         */
        public Builder shippoApiVersion(String shippoApiVersion) {
            Utils.checkNotNull(shippoApiVersion, "shippoApiVersion");
            this.shippoApiVersion = Optional.ofNullable(shippoApiVersion);
            return this;
        }

        /**
         * String used to pick a non-default API version to use
         */
        public Builder shippoApiVersion(Optional<? extends String> shippoApiVersion) {
            Utils.checkNotNull(shippoApiVersion, "shippoApiVersion");
            this.shippoApiVersion = shippoApiVersion;
            return this;
        }
        
        public GetAddressRequest build() {
            return new GetAddressRequest(
                addressId,
                shippoApiVersion);
        }
    }
}

