/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.shippo.shippo_java_sdk.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.core.type.TypeReference;
import com.shippo.shippo_java_sdk.utils.Utils;
import java.io.InputStream;
import java.lang.Deprecated;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.net.http.HttpResponse;
import java.util.Optional;


public class GetDefaultParcelTemplateResponse implements com.shippo.shippo_java_sdk.utils.Response {

    /**
     * HTTP response content type for this operation
     */
    private String contentType;

    /**
     * HTTP response status code for this operation
     */
    private int statusCode;

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    private HttpResponse<InputStream> rawResponse;

    private Optional<? extends com.shippo.shippo_java_sdk.models.components.DefaultParcelTemplate> defaultParcelTemplate;

    @JsonCreator
    public GetDefaultParcelTemplateResponse(
            String contentType,
            int statusCode,
            HttpResponse<InputStream> rawResponse,
            Optional<? extends com.shippo.shippo_java_sdk.models.components.DefaultParcelTemplate> defaultParcelTemplate) {
        Utils.checkNotNull(contentType, "contentType");
        Utils.checkNotNull(statusCode, "statusCode");
        Utils.checkNotNull(rawResponse, "rawResponse");
        Utils.checkNotNull(defaultParcelTemplate, "defaultParcelTemplate");
        this.contentType = contentType;
        this.statusCode = statusCode;
        this.rawResponse = rawResponse;
        this.defaultParcelTemplate = defaultParcelTemplate;
    }
    
    public GetDefaultParcelTemplateResponse(
            String contentType,
            int statusCode,
            HttpResponse<InputStream> rawResponse) {
        this(contentType, statusCode, rawResponse, Optional.empty());
    }

    /**
     * HTTP response content type for this operation
     */
    @JsonIgnore
    public String contentType() {
        return contentType;
    }

    /**
     * HTTP response status code for this operation
     */
    @JsonIgnore
    public int statusCode() {
        return statusCode;
    }

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    @JsonIgnore
    public HttpResponse<InputStream> rawResponse() {
        return rawResponse;
    }

    @JsonIgnore
    public Optional<? extends com.shippo.shippo_java_sdk.models.components.DefaultParcelTemplate> defaultParcelTemplate() {
        return defaultParcelTemplate;
    }

    public final static Builder builder() {
        return new Builder();
    }

    /**
     * HTTP response content type for this operation
     */
    public GetDefaultParcelTemplateResponse withContentType(String contentType) {
        Utils.checkNotNull(contentType, "contentType");
        this.contentType = contentType;
        return this;
    }

    /**
     * HTTP response status code for this operation
     */
    public GetDefaultParcelTemplateResponse withStatusCode(int statusCode) {
        Utils.checkNotNull(statusCode, "statusCode");
        this.statusCode = statusCode;
        return this;
    }

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    public GetDefaultParcelTemplateResponse withRawResponse(HttpResponse<InputStream> rawResponse) {
        Utils.checkNotNull(rawResponse, "rawResponse");
        this.rawResponse = rawResponse;
        return this;
    }

    public GetDefaultParcelTemplateResponse withDefaultParcelTemplate(com.shippo.shippo_java_sdk.models.components.DefaultParcelTemplate defaultParcelTemplate) {
        Utils.checkNotNull(defaultParcelTemplate, "defaultParcelTemplate");
        this.defaultParcelTemplate = Optional.ofNullable(defaultParcelTemplate);
        return this;
    }

    public GetDefaultParcelTemplateResponse withDefaultParcelTemplate(Optional<? extends com.shippo.shippo_java_sdk.models.components.DefaultParcelTemplate> defaultParcelTemplate) {
        Utils.checkNotNull(defaultParcelTemplate, "defaultParcelTemplate");
        this.defaultParcelTemplate = defaultParcelTemplate;
        return this;
    }
    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        GetDefaultParcelTemplateResponse other = (GetDefaultParcelTemplateResponse) o;
        return 
            java.util.Objects.deepEquals(this.contentType, other.contentType) &&
            java.util.Objects.deepEquals(this.statusCode, other.statusCode) &&
            java.util.Objects.deepEquals(this.rawResponse, other.rawResponse) &&
            java.util.Objects.deepEquals(this.defaultParcelTemplate, other.defaultParcelTemplate);
    }
    
    @Override
    public int hashCode() {
        return java.util.Objects.hash(
            contentType,
            statusCode,
            rawResponse,
            defaultParcelTemplate);
    }
    
    @Override
    public String toString() {
        return Utils.toString(GetDefaultParcelTemplateResponse.class,
                "contentType", contentType,
                "statusCode", statusCode,
                "rawResponse", rawResponse,
                "defaultParcelTemplate", defaultParcelTemplate);
    }
    
    public final static class Builder {
 
        private String contentType;
 
        private Integer statusCode;
 
        private HttpResponse<InputStream> rawResponse;
 
        private Optional<? extends com.shippo.shippo_java_sdk.models.components.DefaultParcelTemplate> defaultParcelTemplate = Optional.empty();  
        
        private Builder() {
          // force use of static builder() method
        }

        /**
         * HTTP response content type for this operation
         */
        public Builder contentType(String contentType) {
            Utils.checkNotNull(contentType, "contentType");
            this.contentType = contentType;
            return this;
        }

        /**
         * HTTP response status code for this operation
         */
        public Builder statusCode(int statusCode) {
            Utils.checkNotNull(statusCode, "statusCode");
            this.statusCode = statusCode;
            return this;
        }

        /**
         * Raw HTTP response; suitable for custom response parsing
         */
        public Builder rawResponse(HttpResponse<InputStream> rawResponse) {
            Utils.checkNotNull(rawResponse, "rawResponse");
            this.rawResponse = rawResponse;
            return this;
        }

        public Builder defaultParcelTemplate(com.shippo.shippo_java_sdk.models.components.DefaultParcelTemplate defaultParcelTemplate) {
            Utils.checkNotNull(defaultParcelTemplate, "defaultParcelTemplate");
            this.defaultParcelTemplate = Optional.ofNullable(defaultParcelTemplate);
            return this;
        }

        public Builder defaultParcelTemplate(Optional<? extends com.shippo.shippo_java_sdk.models.components.DefaultParcelTemplate> defaultParcelTemplate) {
            Utils.checkNotNull(defaultParcelTemplate, "defaultParcelTemplate");
            this.defaultParcelTemplate = defaultParcelTemplate;
            return this;
        }
        
        public GetDefaultParcelTemplateResponse build() {
            return new GetDefaultParcelTemplateResponse(
                contentType,
                statusCode,
                rawResponse,
                defaultParcelTemplate);
        }
    }
}

