/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.goshippo.shippo_sdk;

import static com.goshippo.shippo_sdk.operations.Operations.RequestOperation;

import com.goshippo.shippo_sdk.models.components.ShippoAccountUpdateRequest;
import com.goshippo.shippo_sdk.models.operations.CreateShippoAccountRequestBuilder;
import com.goshippo.shippo_sdk.models.operations.CreateShippoAccountResponse;
import com.goshippo.shippo_sdk.models.operations.GetShippoAccountRequest;
import com.goshippo.shippo_sdk.models.operations.GetShippoAccountRequestBuilder;
import com.goshippo.shippo_sdk.models.operations.GetShippoAccountResponse;
import com.goshippo.shippo_sdk.models.operations.ListShippoAccountsRequest;
import com.goshippo.shippo_sdk.models.operations.ListShippoAccountsRequestBuilder;
import com.goshippo.shippo_sdk.models.operations.ListShippoAccountsResponse;
import com.goshippo.shippo_sdk.models.operations.UpdateShippoAccountRequest;
import com.goshippo.shippo_sdk.models.operations.UpdateShippoAccountRequestBuilder;
import com.goshippo.shippo_sdk.models.operations.UpdateShippoAccountResponse;
import com.goshippo.shippo_sdk.operations.CreateShippoAccount;
import com.goshippo.shippo_sdk.operations.GetShippoAccount;
import com.goshippo.shippo_sdk.operations.ListShippoAccounts;
import com.goshippo.shippo_sdk.operations.UpdateShippoAccount;
import com.goshippo.shippo_sdk.utils.Headers;
import java.lang.Long;
import java.lang.String;
import java.util.Optional;

/**
 * Shippo Accounts are used by Shippo Platform Accounts to create and manage Managed Shippo Accounts.
 * Managed Shippo Accounts are headless accounts that represent your customers. They are opaque to your
 * end customers, meaning customers do not need to create their own Shippo login or have a billing
 * relationship with Shippo.
 * They can be used by marketplaces, e-commerce platforms, and third-party logistics providers who want
 * to offer, seamless, built-in shipping functionality to their customers. See our
 * [guide](https://docs.goshippo.com/docs/platformaccounts/platform_accounts/) for more details.
 */
public class ShippoAccounts {
    private static final Headers _headers = Headers.EMPTY;
    private final SDKConfiguration sdkConfiguration;

    ShippoAccounts(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
    }

    /**
     * List all Shippo Accounts
     * 
     * <p>Returns a list of Shippo Managed Accounts objects.
     * 
     * @return The call builder
     */
    public ListShippoAccountsRequestBuilder list() {
        return new ListShippoAccountsRequestBuilder(sdkConfiguration);
    }

    /**
     * List all Shippo Accounts
     * 
     * <p>Returns a list of Shippo Managed Accounts objects.
     * 
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public ListShippoAccountsResponse listDirect() {
        return list(Optional.empty(), Optional.empty());
    }

    /**
     * List all Shippo Accounts
     * 
     * <p>Returns a list of Shippo Managed Accounts objects.
     * 
     * @param page The page number you want to select
     * @param results The number of results to return per page (max 100)
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public ListShippoAccountsResponse list(Optional<Long> page, Optional<Long> results) {
        ListShippoAccountsRequest request =
            ListShippoAccountsRequest
                .builder()
                .page(page)
                .results(results)
                .build();
        RequestOperation<ListShippoAccountsRequest, ListShippoAccountsResponse> operation
              = new ListShippoAccounts.Sync(sdkConfiguration, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * Create a Shippo Account
     * 
     * <p>Creates a new [Shippo Managed
     * Account](https://docs.goshippo.com/docs/platformaccounts/platform_using_accounts/).
     * 
     * @return The call builder
     */
    public CreateShippoAccountRequestBuilder create() {
        return new CreateShippoAccountRequestBuilder(sdkConfiguration);
    }

    /**
     * Create a Shippo Account
     * 
     * <p>Creates a new [Shippo Managed
     * Account](https://docs.goshippo.com/docs/platformaccounts/platform_using_accounts/).
     * 
     * @param email 
     * @param firstName 
     * @param lastName 
     * @param companyName 
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public CreateShippoAccountResponse create(
            String email, String firstName,
            String lastName, String companyName) {
        ShippoAccountUpdateRequest request =
            ShippoAccountUpdateRequest
                .builder()
                .email(email)
                .firstName(firstName)
                .lastName(lastName)
                .companyName(companyName)
                .build();
        RequestOperation<ShippoAccountUpdateRequest, CreateShippoAccountResponse> operation
              = new CreateShippoAccount.Sync(sdkConfiguration, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * Retrieve a Shippo Account
     * 
     * <p>Returns a Shippo Managed Account using an object ID.
     * 
     * @return The call builder
     */
    public GetShippoAccountRequestBuilder get() {
        return new GetShippoAccountRequestBuilder(sdkConfiguration);
    }

    /**
     * Retrieve a Shippo Account
     * 
     * <p>Returns a Shippo Managed Account using an object ID.
     * 
     * @param shippoAccountId Object ID of the ShippoAccount
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public GetShippoAccountResponse get(String shippoAccountId) {
        GetShippoAccountRequest request =
            GetShippoAccountRequest
                .builder()
                .shippoAccountId(shippoAccountId)
                .build();
        RequestOperation<GetShippoAccountRequest, GetShippoAccountResponse> operation
              = new GetShippoAccount.Sync(sdkConfiguration, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * Update a Shippo Account
     * 
     * <p>Updates a Shippo Managed Account using an object ID.
     * 
     * @return The call builder
     */
    public UpdateShippoAccountRequestBuilder update() {
        return new UpdateShippoAccountRequestBuilder(sdkConfiguration);
    }

    /**
     * Update a Shippo Account
     * 
     * <p>Updates a Shippo Managed Account using an object ID.
     * 
     * @param shippoAccountId Object ID of the ShippoAccount
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public UpdateShippoAccountResponse update(String shippoAccountId) {
        return update(shippoAccountId, Optional.empty());
    }

    /**
     * Update a Shippo Account
     * 
     * <p>Updates a Shippo Managed Account using an object ID.
     * 
     * @param shippoAccountId Object ID of the ShippoAccount
     * @param shippoAccountUpdateRequest 
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public UpdateShippoAccountResponse update(String shippoAccountId, Optional<? extends ShippoAccountUpdateRequest> shippoAccountUpdateRequest) {
        UpdateShippoAccountRequest request =
            UpdateShippoAccountRequest
                .builder()
                .shippoAccountId(shippoAccountId)
                .shippoAccountUpdateRequest(shippoAccountUpdateRequest)
                .build();
        RequestOperation<UpdateShippoAccountRequest, UpdateShippoAccountResponse> operation
              = new UpdateShippoAccount.Sync(sdkConfiguration, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

}
